language: python
python:
  - 3.8

install:
  - pip install pylint

script:
  - python -m pip install .
  - pylint --rcfile test/pylint.rc peakrdl

stages:
  - test
  # Only execute deployment stage on tagged release commits in the form of "v1.2.3"
  # and from your repository (e.g. not PRs).
  # Also allows alpha/beta releases such as "v1.2.3b2"
  - name: deploy
    if: repo = SystemRDL/PeakRDL-html AND tag =~ ^v\d+\.\d+\.\w+$

jobs:
  include:
    # Deploy source distribution
    - stage: deploy
      name: Deploy source distribution
      install: python -m pip install twine
      script: python setup.py sdist --formats=gztar
      after_success: python -m twine upload --skip-existing dist/*.tar.gz
